### ISSUE TITLE
Difference between the "show from <x>" transitions?

### ISSUE THREAD

**Issue by anthonywebb** [JedWatson/touchstonejs#21]
I am not able to spot any difference between the various transitions that start with "show from" (left, right, top, bottom)  Should there be any difference?  It just seems to go to the next view without any transition at all?

**Comment by jossmac** [comment]
Hi Anthony,

This is a peculiar bug with mobile Safari that we're looking into related to touch events. If you checkout the demo http://demo.touchstonejs.io on your desktop you'll be able to see the transitions described.

Also if you fork the repo and build the app with Xcode you'll get the true experience :)

**Comment by anthonywebb** [comment]
Ah, I see, thanks!
