### ISSUE TITLE
Progress/Spinner

### ISSUE THREAD

**Issue by anthonywebb** [JedWatson/touchstonejs#23]
I currently have an app that pull data from a web service.  I would love to have a way to launch a progress or spinner to let the user know that things have not hung.  Any plans for this kind of thing?  I didnt notice it on the roadmap.

**Comment by jossmac** [comment]
Hi Anthony,

This was part of the demo but I'd commented it out, oops! I've updated the site http://demo.touchstonejs.io, you can now find it under the UI Elements heading.

**Comment by jossmac** [comment]
Added loading spinner to the demo in 0cdae2f
