### ISSUE TITLE
Consider swapping Underscore with Lo-Dash

### ISSUE THREAD

**Issue by omarshibli** [JedWatson/touchstonejs#33]

**Comment by DrMabuse23** [comment]
i think Ramda is the better opinion !

**Comment by DrMabuse23** [comment]
sorry i mean the faster

**Comment by morenoh149** [comment]
I'd think they'd sooner move to lodash. Frist I've heard of ramda. looks very cool. will try

**Comment by DrMabuse23** [comment]
http://fr.umio.us/the-philosophy-of-ramda/

**Comment by JedWatson** [comment]
@DrMabuse23 Ramda looks cool (and I will look into it further) but from that post you linked to:

> It's inevitable that Ramda will be compared to Underscore and lodash; the functions supplied overlap in capability and function names. But Ramda will never be a drop-in replacement for those libraries.

... so I think that is a different discussion, it would require a nontrivial rework of how we program.

Back on topic: yes, moving to loadsh is definitely something we will do in the not too distant future.

**Comment by DrMabuse23** [comment]
Cool for me is lodash a great tool too!  Let me know you guys need help

**Comment by dcousens** [comment]
Removed underscore dependency all together.  All we were really using was functionality that exists in https://github.com/Raynos/xtend anyway.
