### ISSUE TITLE
Outdated gulp-less version produces build error

### ISSUE THREAD

**Issue by Way** [JedWatson/touchstonejs#44]
In the **touchstonejs-tasks** module the *"gulp-less"* dependency uses an outdated version *"^2.0.2"* which leads to a known error with nodejs version 0.12.x: https://github.com/plus3network/gulp-less/issues/140

**Fix**: Update the gulp-less dependencie to the latest *"3.0.1"* version and the less task will run successfully.

**Comment by dcousens** [comment]
Fixed by #46
