### ISSUE TITLE
Can't build ionic

### ISSUE THREAD

**Issue by amay0048** [JedWatson/touchstonejs#53]
I'm trying to build my ionic project, but it wont include my images, should I include react?

**Comment by giantelk** [comment]
Isn't Ionic for AngularJS only? TouchStoneJS is for ReactJS!

On Fri, Mar 27, 2015 at 3:41 AM, amay0048 <notifications@github.com> wrote:

> I'm trying to build my ionic project, but it wont include my images,
> should I include react?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JedWatson/touchstonejs/issues/53>.
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by jossmac** [comment]
Just realised who this was. Well played.
