### ISSUE TITLE
Closing native keyboard on ipad causes content 'clipping' until next screen event

### ISSUE THREAD

**Issue by gregtillbrook** [JedWatson/touchstonejs#56]
Hi, has anyone played with Touchstone on iPad much yet? Ive noticed an ugly artefact when using native keyboards such that after they slide away, content becomes clipped (about half a screens worth) and doesn't redraw until you touch the screen/change orientation etc.

I'll investigate the issue some more but wanted to mention it now incase it's a known issue.

To reproduce; load the touchstone sample app onto an iPad (mine was a 4th Gen - late 2012), go to the 'Form Fields' section and click an input, click on the screen to make the keyboard go away, clipping bug should be visible.

**Comment by gregtillbrook** [comment]
So it's _looking_ like this is a Cordova or possibly a mobile safari bug. It seems to be the same issue raised here;
http://stackoverflow.com/questions/18970865/ios-7-input-elements-moving-fixed-positioned-elements

It seems like the positioning of position:fixed elements is buggy when the keyboard is closed and isn't corrected until you touch the page. Oddly, everything works fine if you hide the keyboard by pressing the 'close keyboard' button rather than touching the page...

For now Im using this (ugly) workaround;
```
$(document).on('blur', 'input, textarea', function () {
    setTimeout(function () {
        window.scrollTo(document.body.scrollLeft, document.body.scrollTop);
    }, 0);
});
```

**Comment by jossmac** [comment]
@gregtillbrook what version of Touchstone are you using?

We fixed a bunch of bugs with the keyboard behaviour for a recent project - they're all in 0.2.0

**Comment by gregtillbrook** [comment]
Ah ha - yes indeed. Id been working from the sample project and hadn't realised it was lagging behind. Not seeing this bug now Im in 0.2.0.

Cheers!

**Comment by gregtillbrook** [comment]
Incidentally (for anyone else that grabs the sample project and fetches the latest touchstone ver) I did also hit an ios7 bug where the device-height is wrong in landscape mode. The fix was to remove `height=device-height` from my meta viewport tag
