### ISSUE TITLE
why not cache navigation history?

### ISSUE THREAD

**Issue by Duan112358** [JedWatson/touchstonejs#60]
navigation history was not cached or hashed in url.

so when page refresh ,  page got navigated to default view
why not enabled feature like [react-router](https://github.com/rackt/react-router)?

**Comment by dcousens** [comment]
History may not always be relevant to an application.   In fact,  using touchstone, you could optionally add it yourself or avoid it entirely.   I think we should keep the core as clean as possible to avoid feature creep, while creating sub-components that we can easily attach to enable these features without issue.
